import cv2
import numpy as np

birdimage=cv2.imread("class 35\\bird.jpg")
cv2.imshow("bird",birdimage)
cv2.waitKey(0)
cv2.destroyAllWindows()
resizeimg=cv2.resize(birdimage,(500,500))
cv2.imshow("resized image",resizeimg)
cv2.waitKey(0)
cv2.destroyAllWindows()
borderimg=cv2.copyMakeBorder(resizeimg,20,20,20,20,borderType=cv2.BORDER_CONSTANT,value=(255,0,0))
cv2.imshow("bordered image",borderimg)
cv2.waitKey(0)
cv2.destroyAllWindows()
greyimg=cv2.cvtColor(resizeimg,cv2.COLOR_BGR2GRAY)
cv2.imshow("grey image",greyimg)
cv2.waitKey(0)
cv2.destroyAllWindows()
hsvimg=cv2.cvtColor(resizeimg,cv2.COLOR_BGR2HSV)
cv2.imshow("hsv image",hsvimg)
cv2.waitKey(0)
cv2.destroyAllWindows()
b,g,r=cv2.split(resizeimg)
zeroarray=np.zeros_like(resizeimg)

blueimg=cv2.merge([b,zeroarray,zeroarray])
cv2.imshow("blue image",b)
cv2.waitKey(0)
cv2.destroyAllWindows()